version: 2.1
orbs:
    azure-cli: johnstonjacob/azure-cli@0.1.0

jobs:
    build:
        docker: 
          - image: circleci/node
        steps:
          - azure-cli/install
          - run: 
                name: Verify Azure install
                command: az -v
          - azure-cli/login-with-user
          - run: 
                name: Verify login with user
                command: az resource list 
          - run: az logout
          - azure-cli/login-with-service-principal:
              azure-username: $AZURE_SP_NAME
              azure-password: $AZURE_SP_PASSWORD
              azure-tenant: $AZURE_SP_TENANT
          - run: 
                name: Verify login with Service Principal
                command: az resource list 
          - run: az logout
          - azure-cli/login-with-user:
              alternate-tenant: true
              azure-tenant: $AZURE_SP_TENANT
          - run: 
                name: Verify login with user and alternate tenant
                command: az resource list 
