version: 2.1
orbs:
    azure-cli: johnstonjacob/azure-cli@dev:0.0.2
    circleci-cli: circleci/circleci-cli@0.0.1

commands:
    azure-cli-tests:
        description: "Verifies azure-cli install"
        steps:
            - azure-cli/install
            - run: 
                  name: Verify Azure install
                  command: az -v
            - azure-cli/login-with-user
            - run: 
                  name: Verify login with user
                  command: az resource list 
            - run: az logout
            - azure-cli/login-with-service-principal:
                azure-username: $AZURE_SP_NAME
                azure-password: $AZURE_SP_PASSWORD
                azure-tenant: $AZURE_SP_TENANT
            - run: 
                  name: Verify login with Service Principal
                  command: az resource list 
            - run: az logout
            - azure-cli/login-with-user:
                alternate-tenant: true
                azure-tenant: $AZURE_SP_TENANT
            - run: 
                  name: Verify login with user and alternate tenant
                  command: az resource list 

jobs:
    validate-orb:
        docker:
            - image: circleci/python:2.7-stretch
        steps:
            - checkout
            - circleci-cli/install
            - run:
                name: Validate orb
                command: |
                    circleci orb validate src/orb.yml
    publish-dev:
        docker: 
            - image: circleci/python:2.7-stretch
        steps:
            - checkout
            - circleci-cli/install
            - run:
                name: Authenticate with CircleCI
                command: circleci setup --token $CIRCLECI_CLI_TOKEN
            - run:
                name: Publish dev orb
                command: circleci orb publish src/orb.yml johnstonjacob/azure-cli@dev:0.0.2
    test-orb:
        docker: 
            - image: circleci/python:2.7-stretch
        steps:
            - azure-cli-tests
    test-orb-non-python:
        docker: 
            - image: circleci/golang
        steps:
            - azure-cli-tests
    test-orb-docker-executor:
        executor: azure-cli/azure-docker
        steps:
            - azure-cli-tests
workflows:
    build-deploy:
        jobs:
            - validate-orb
            - publish-dev:
                requires:
                    - validate-orb
            - test-orb-non-python:
                requires:
                    - publish-dev
            - test-orb:
                requires:
                    - publish-dev
            - test-orb-docker-executor:
                requires:
                    - publish-dev
